asn_local = input('Qual o número do ASN local? ')
asn_remote = input('Qual o número do ASN remoto? ')
group = input('Qual o nome do seu peer group? ')
peer = input('Qual o endereco do peer? ')
print()
print('#')
print('route-policy IN-IPv4-'+group +' deny node 1')
print('route-policy OUT-IPv4-'+group +' deny node 1')
print('#')
print("bgp "+asn_local)
print('peer '+group+' as-number '+asn_remote)
print('peer '+group+' advertise-community')
print('peer '+peer+' group '+group)
print('peer '+group+' route-policy IN-IPv4-'+group+' import')
print('peer '+group+' route-policy OUT-IPv4-'+group+' export')
